packages:
  - 'packages/*'
  - 'playground'


catalog:
    typescript: ~5.8.3
    vite: ^6.3.0
    "@sxzz/eslint-config": ^7.0.4
    "@sxzz/prettier-config": ^2.2.1
    eslint: ^9.30.1
    prettier: ^3.6.0
    "@iconify/tools": ^4.1.2
    "@iconify/types": ^2.0.0
    "esno": ^4.8.0
    "@unocss/preset-mini": 66.1.0-beta.10
    "@unocss/vite": 66.1.0-beta.10
    "@unocss/reset": 66.1.0-beta.10
    unocss: 66.1.0-beta.10
    "vite-plugin-solid": ^2.11.7
    "@figma/plugin-typings": ^1.116.0
    "@types/node": ^24.1.0
    '@types/prettier': 3.0.0
    "cross-env": ^10.0.0
    "vite-figma-plugin": ^0.0.24
    "vite-plugin-singlefile": ^2.3.0
    "solid-js": ^1.9.7
    "@iconify-json/carbon": ^1.2.11
    "@iconify-icon/solid": ^3.0.0

