name: cicd

on:
  push:
    branches:
      - test-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run something
        run: echo "CICD for test-cicd branch!"

      - name: Get repo website
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log("Website:", repo.data);