name: cicd

on:
  push:
    branches:
      - test-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repo website
        id: repo-info
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('component_url', repo.data.homepage || '');

      - name: Get releases info
        id: releases-info
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            if (releases.data.length > 0) {
              const latest = releases.data[0];
              const regex = /@([\w-]+\/[\w-]+)/;
              const match = latest.body.match(regex);
              core.setOutput('component_name', match ? match[0] : '');
              core.setOutput('component_version', latest.tag_name);
            } else {
              core.setOutput('component_name', '');
              core.setOutput('component_version', '');
            }

      - name: Use component info
        run: |
          echo "component_url=${{ steps.repo-info.outputs.component_url }}"
          echo "component_name=${{ steps.releases-info.outputs.component_name }}"
          echo "component_version=${{ steps.releases-info.outputs.component_version }}"